version: '3.3'

services:
  jamulus-pi:
    image: jamulus-pi
    restart: unless-stopped
    hostname: jamulus-pi
    container_name: jamulus-pi
    ports:
      - "22124:22124/udp"
    stdin_open: true
    tty: true