version: '3.3'

services:
  jamulus-pi:
    image: cimlah/jamulus-pi:latest
    restart: unless-stopped
    hostname: jamulus-pi1
    container_name: jamulus-pi1
    ports:
      - "22124:22124/udp"
    stdin_open: true
    tty: true